// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.6
//   protoc               v5.29.3
// source: shared/common.proto

/* eslint-disable */

export const protobufPackage = "shared.common";

/** Standard empty response for operations that don't return data */
export interface Empty {
}

/** Standard success/error response pattern */
export interface StandardResponse {
  success: boolean;
  message: string;
  errorCode?: string | undefined;
}

/** Timestamp wrapper for consistent date handling */
export interface Timestamp {
  /** ISO 8601 formatted timestamp */
  value: string;
}

/** Standard pagination request */
export interface PaginationRequest {
  page: number;
  limit: number;
  cursor?: string | undefined;
}

/** Standard pagination response metadata */
export interface PaginationMeta {
  currentPage: number;
  totalPages: number;
  totalItems: number;
  nextCursor?: string | undefined;
  prevCursor?: string | undefined;
}

/** Standard error details */
export interface ErrorDetail {
  field: string;
  message: string;
  code: string;
}

/** Validation error response */
export interface ValidationError {
  message: string;
  details: ErrorDetail[];
}

export const SHARED_COMMON_PACKAGE_NAME = "shared.common";
