// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.6
//   protoc               v5.29.3
// source: shared/location.proto

/* eslint-disable */

export const protobufPackage = "shared.location";

/** Standardized location coordinates */
export interface Location {
  /** Latitude */
  lat: number;
  /** Longitude (standardized to 'lng' instead of 'long') */
  lng: number;
}

/** Bounding box for area-based queries */
export interface BoundingBox {
  northeast: Location | undefined;
  southwest: Location | undefined;
}

/** Address information */
export interface Address {
  street: string;
  city: string;
  state: string;
  postalCode: string;
  country: string;
  formattedAddress?: string | undefined;
}

/** Complete location with coordinates and address */
export interface FullLocation {
  coordinates: Location | undefined;
  address?: Address | undefined;
}

export const SHARED_LOCATION_PACKAGE_NAME = "shared.location";
