// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v1.181.1
//   protoc               v5.27.3
// source: index.proto

/* eslint-disable */

export const protobufPackage = "";

export const _PACKAGE_NAME = "";
