// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.6
//   protoc               v5.29.3
// source: index.proto

/* eslint-disable */

export const protobufPackage = "";

export const _PACKAGE_NAME = "";
