export const ErrorCodes = {
	ALGOLIA_SERVICE_ERROR: 'Search service error',
	CLERK_SERVICE_ERROR: 'Authentication service error',
	COMMUNICATION_INVALID_WEBHOOK_SIGNATURE: 'Invalid webhook signature',
	DATABASE_ERROR: 'Database operation failed',
	FILE_TOO_LARGE: 'File size too large',
	INTERNAL_SERVER_ERROR: 'Internal server error',
	INVALID_FILE_TYPE: 'Invalid file type',
	INVALID_INPUT: 'Invalid input data',
	INVALID_SUBSCRIPTION_DATA: 'Invalid subscription data',
	INVALID_USER_DATA: 'Invalid user data',
	INVALID_VENDOR_DATA: 'Invalid vendor data',
	LOCATION_INVALID_COORDINATES: 'Invalid location coordinates',
	LOCATION_QUERY_FAILED: 'Location query failed',
	LOCATION_REDIS_OPERATION_FAILED: 'Location Redis operation failed',
	LOCATION_UPDATE_FAILED: 'Location update failed',
	NATS_PUBLISH_FAILED: 'Failed to publish NATS event',
	NATS_SUBSCRIBE_FAILED: 'Failed to subscribe to NATS event',
	REDIS_OPERATION_FAILED: 'Redis operation failed',
	SUBSCRIPTION_CREATION_FAILED: 'Failed to create subscription',
	SUBSCRIPTION_DELETION_FAILED: 'Failed to delete subscription',
	SUBSCRIPTION_UPDATE_FAILED: 'Failed to update subscription',
	UPLOAD_FAILED: 'File upload failed',
	USER_CREATION_FAILED: 'Failed to create user',
	USER_DELETION_FAILED: 'Failed to delete user',
	USER_NOT_FOUND: 'User not found',
	USER_UPDATE_FAILED: 'Failed to update user',
	VENDOR_CREATION_FAILED: 'Failed to create vendor',
	VENDOR_DELETION_FAILED: 'Failed to delete vendor',
	VENDOR_LIMIT_EXCEEDED: 'Vendor limit exceeded',
	VENDOR_NOT_FOUND: 'Vendor not found',
	VENDOR_UNAUTHORIZED: 'Unauthorized vendor operation',
	VENDOR_UPDATE_FAILED: 'Failed to update vendor',
	WS_RATE_LIMIT_EXCEEDED: 'WebSocket rate limit exceeded',
} as const;
