export const ErrorCodes = {
	WEBHOOK_PROCESSING_FAILED: 'Failed to process webhook',
	USER_OPERATION_FAILED: 'User operation failed',
	INVALID_VENDOR_ID: 'Invalid vendor ID',
	INVALID_VENDOR_DATA: 'Invalid vendor data',
	INVALID_LOCATION_DATA: 'Invalid location data',
	VENDOR_OPERATION_FAILED: 'Vendor operation failed',
	USER_VENDORS_RETRIEVAL_FAILED: 'Failed to get user vendors',
	ALGOLIA_SERVICE_ERROR: 'Search service error',
	ALGOLIA_SYNC_FAILED: 'Failed to sync with search service',
	CLERK_SERVICE_ERROR: 'Authentication service error',
	COMMUNICATION_INVALID_WEBHOOK_SIGNATURE: 'Invalid webhook signature',
	DATABASE_ERROR: 'Database operation failed',
	INVALID_DOMAIN_EVENT: 'Invalid domain event',
	INVALID_FILE_TYPE: 'Invalid file type',
	INVALID_INDEX_TYPE: 'Invalid search index type',
	INVALID_INPUT: 'Invalid input data',
	INVALID_LOCATION_UPDATE: 'Invalid location update',
	INVALID_PAYLOAD: 'Invalid webhook payload',
	INVALID_SEARCH_RECORD: 'Invalid search record',
	INVALID_SEARCH_UPDATE: 'Invalid search update',
	INVALID_SIGNATURE: 'Invalid webhook signature',
	INVALID_SUBSCRIPTION_DATA: 'Invalid subscription data',
	INVALID_SUBSCRIPTION_OPTIONS: 'Invalid subscription options',
	INVALID_USER_DATA: 'Invalid user data',
	INVALID_VENDOR_DATA: 'Invalid vendor data',
	LOCATION_INVALID_COORDINATES: 'Invalid location coordinates',
	LOCATION_QUERY_FAILED: 'Location query failed',
	LOCATION_REDIS_OPERATION_FAILED: 'Location Redis operation failed',
	LOCATION_UPDATE_FAILED: 'Location update failed',
	NATS_OPERATION_FAILED: 'NATS operation failed',
	NATS_PUBLISH_FAILED: 'Failed to publish NATS event',
	NATS_SUBSCRIBE_FAILED: 'Failed to subscribe to NATS event',
	NATS_SUBSCRIPTION_FAILED: 'Failed to initialize NATS subscriptions',
	REDIS_OPERATION_FAILED: 'Redis operation failed',
	SUBSCRIPTION_CREATION_FAILED: 'Failed to create subscription',
	SUBSCRIPTION_DELETION_FAILED: 'Failed to delete subscription',
	SUBSCRIPTION_UPDATE_FAILED: 'Failed to update subscription',
	UPLOAD_FAILED: 'File upload failed',
	USER_CREATION_FAILED: 'Failed to create user',
	USER_DELETION_FAILED: 'Failed to delete user',
	USER_NOT_FOUND: 'User not found',
	USER_UPDATE_FAILED: 'Failed to update user',
	VENDOR_CREATION_FAILED: 'Failed to create vendor',
	VENDOR_DELETION_FAILED: 'Failed to delete vendor',
	VENDOR_LIMIT_EXCEEDED: 'Vendor limit exceeded',
	VENDOR_NOT_FOUND: 'Vendor not found',
	VENDOR_UNAUTHORIZED: 'Unauthorized vendor operation',
	VENDOR_UPDATE_FAILED: 'Failed to update vendor',
	WS_RATE_LIMIT_EXCEEDED: 'WebSocket rate limit exceeded',
} as const;
